### ISSUE TITLE
derzeitige Modliste wirft fehler.

### ISSUE THREAD

**Issue by ruffst** [ruffst/DZL-Survival-Pack-Overlay#1]
Es könnte an der Ladereihenfolge liegen oder auch an einem speziellen Mod. Müsste man erst prüfen bevor man die Arbeit am Overlay beginnt.

**Comment by CaptainHarlock0006** [comment]
Jo das klingt nach nem Plan.  erstmal die Mods alle runter ziehen dann schauen und analysieren.

**Comment by ruffst** [comment]
Hier noch die Errorlog vom Torch

[Keen-2023-08-04.log](https://github.com/ruffst/DZL-Survival-Pack-Overlay/files/12265998/Keen-2023-08-04.log)

**Comment by ruffst** [comment]
Kritische Fehler kommen von:

Epstein Drive Thruster
Automatic Ore Pickup
Atmospheric Drag & Re-Entry Effects
Tiered Storage Tanks

Nicht unwesentliche Fehler 
Scarce Resources
Thrust Engines v3 (Modpack) [2x, 5x, 10x]
Electronics Panel - small blocks on large grid

Ich nehm die mal raus und schau nochmal

**Comment by ruffst** [comment]
erledigt

**Comment by Yosaaaaa** [comment]
1
